ARTICLES_PER_PAGE = 5
DATABASE_NAME = 'mrshoeblog'
COMMENTS_ENABLED = False
GOOGLE_ANALYTICS_ACCOUNT = 'UA-168882-1'
BLOGGER_NAME = 'David Shoemaker'
BLOG_TITLE = 'MrShoe.org Blog'
HOME_URL = 'http://mrshoe.org/'
BLOG_URL = 'http://mrshoe.org/blog/'
ATOM_URL = 'http://mrshoe.org/blog/index.xml'
BLOG_PASSWORD = open('passwd').read().strip()
